# 项目信息
repo_name: "fastapi_vue3_admin" # 源码名称
repo_url: "https://github.com/1014TaoTao/fastapi_vue3_admin.git" # 源码地址

site_name: Fastapi_Vue3_Admin在线文档 # 网站名称
site_author: 948080782x@qq.com # 网站作者
site_description: 这里是网站描述 # 网站描述
copyright: 'Copyright © 2022 <a href="https://github.com/1014TaoTao/fastapi_vue3_admin">Powered by 948080782x@qq.com 版权所有</a>' # 版权信息
use_directory_urls: false # 禁止生成的 URL 使用目录形式，默认为 true

# 主题配置
theme:
  name: material # 使用 Material 主题
  language: zh # 配置语言为中文
  features:
    - navigation.tabs # 启用标签页
    - navigation.tabs.sticky # 固定标签页
    - navigation.instant # 启用即时导航
    - search.highlight # 搜索高亮
    - search.suggest # 启用搜索建议
    - navigation.footer # 显示底部导航
    - toc.integrate # 启用集成目录
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - content.code.copy #代码复制
  highlightjs: true # 启用代码高亮

# 导航菜单
nav:
  - 帮助文档: index.md

# 插件配置
plugins:
  - search
